---
openapi: 3.0.1
info:
  title: Bicycle appointment API
  description: ''
  version: v1
security:
  - bearerAuth: []
paths:
  "/api/v1/login":
    post:
      summary: login auth
      parameters: []
      responses:
        '201':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/api/v1/motorbikes":
    get:
      summary: list motorbikes
      responses:
        '200':
          description: successful
    post:
      summary: create motorbike
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                model:
                  type: string
                image:
                  type: string
                price:
                  type: number
                description:
                  type: string
              required:
              - name
              - model
              - price
  "/api/v1/motorbikes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show motorbike
      responses:
        '200':
          description: successful
    delete:
      summary: delete motorbike
      responses:
        '200':
          description: successful
  "/api/v1/users":
    post:
      summary: create user
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                  required:
                  - username
                  - password
              required:
              - user
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT