---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/motorbikes":
    get:
      summary: list motorbikes
      responses:
        '200':
          description: successful
    post:
      summary: create motorbike
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                model:
                  type: string
                image:
                  type: string
                price:
                  type: number
                description:
                  type: string
              required:
              - name
              - model
              - price
  "/api/v1/motorbikes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show motorbike
      responses:
        '200':
          description: successful
    delete:
      summary: delete motorbike
      responses:
        '200':
          description: successful
  "/api/v1/reservations":
    post:
      summary: create reservation
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                city:
                  type: string
                motorbike_id:
                  type: integer
                user_id:
                  type: integer
              required:
              - date
              - city
              - motorbike_id
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/v1/users":
    post:
      summary: create user
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
